apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: expressapplication
  description: An Express.js application developed by KeertiPusarlaa, designed to handle HTTP requests and provide a robust backend service.
  annotations:
    github.com/project-slug: KeertiPusarlaa/expressapplication
    jira/project-key: SCRUM
    jira/label: backstage-component:expressapplication
spec:
  type: application
  owner: ICS
  lifecycle: experimental